### ISSUE TITLE
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by habreu71** [knrd1/chatgpt#20]
Hi,

I'm using OpenBSD 7.2 and get the error below when I run python3 chatgpt.py. I think OpenBSD uses LibreSSL even when OpenSSL is invoked, please let me know any update or orientation you can provide. Thank you in advance.

$ python3 chatgpt.py
Traceback (most recent call last):
  File "/home/habreu/chatgpt/chatgpt.py", line 1, in <module>
    import openai
  File "/home/habreu/.local/lib/python3.9/site-packages/openai/__init__.py", line 19, in <module>
    from openai.api_resources import (
  File "/home/habreu/.local/lib/python3.9/site-packages/openai/api_resources/__init__.py", line 1, in <module>
    from openai.api_resources.audio import Audio  # noqa: F401
  File "/home/habreu/.local/lib/python3.9/site-packages/openai/api_resources/audio.py", line 4, in <module>
    from openai import api_requestor, util
  File "/home/habreu/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 22, in <module>
    import requests
  File "/home/habreu/.local/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/habreu/.local/lib/python3.9/site-packages/urllib3/__init__.py", line 38, in <module>
    raise ImportError(
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 3.6.0. See: https://github.com/urllib3/urllib3/issues/2168

**Comment by knrd1** [comment]
Apologies for delays. I just added instructions how to build and run the bot in Docker container. I think that's the only option left for BSD users. Unfortunately I have no experience with BSD systems and can't be of help here.
