### ISSUE TITLE
Crash after many minutes not answer for question

### ISSUE THREAD

**Issue by takenek** [knrd1/chatgpt#3]
Hey,
I am not sure this is a bot problem or maybe this is API issue but i but do not answer for question and leave IRC with "timeout" 
14:34 -!- Zygmunt [~Zygmunt@xxx.pl] has quit [Ping timeout]
and after another few minutes he crash:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 672, in _interpret_response_line
    data = json.loads(rbody)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/chatgpt/./chatgpt.py", line 31, in <module>
    response = openai.Completion.create(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 674, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
)

```

**Comment by takenek** [comment]
So maybe add support for 502/500 errors? and ofc handling timeouts.

**Comment by knrd1** [comment]
I will take care of it this week, thanks for reporting all the issues!
